---
ATL1:
  Integer:
    rule: value <= 240
    # rule: value >= 100
    # rule: value == 100
    # rule: value > 100
    # rule: value < 100
    # rule: value != 100
ATL2:
  String:
    rule: value != LOW
    # rule: value == HIGH
    # rule: value != 124
ATL3:
  Datetime:
    # rule: after 2017-08-20
    # rule: today
    # rule: future
    # rule: _future
    # rule: past
    rule: _past
    # rule: between YYYY-MM-DD YYYY-MM-DD
    # rule: _between YYYY-MM-DD YYYY-MM-DD
    # rule: before YYYY-MM-DD
    # rule: after YYYY-MM-DD
  Integer:
    rule: value > 0